export const managedSites = [
  {
    siteKey: 'dh-portal',
    name: 'DH Staff Portal',
    category: 'internal_app',
    repoUrl: 'https://github.com/dhwebservices/dh-portal-v2',
    githubRepo: 'dhwebservices/dh-portal-v2',
    cloudflareProject: 'dh-portal-v2',
    maintenanceSupported: true,
    environments: [
      {
        envKey: 'production',
        label: 'Production',
        baseUrl: 'https://staff.dhwebsiteservices.co.uk',
        healthUrl: 'https://staff.dhwebsiteservices.co.uk',
        loginUrl: 'https://staff.dhwebsiteservices.co.uk',
        envType: 'production',
      },
      {
        envKey: 'preview',
        label: 'Preview',
        baseUrl: null,
        healthUrl: null,
        envType: 'preview',
      },
    ],
  },
  {
    siteKey: 'dh-client-portal',
    name: 'DH Client Portal',
    category: 'client_portal',
    repoUrl: 'https://github.com/dhwebservices/dh-client-portal',
    githubRepo: 'dhwebservices/dh-client-portal',
    cloudflareProject: 'dh-client-portal',
    maintenanceSupported: true,
    environments: [
      {
        envKey: 'production',
        label: 'Production',
        baseUrl: 'https://app.dhwebsiteservices.co.uk',
        healthUrl: 'https://app.dhwebsiteservices.co.uk',
        loginUrl: 'https://app.dhwebsiteservices.co.uk',
        envType: 'production',
      },
      {
        envKey: 'preview',
        label: 'Preview',
        baseUrl: null,
        healthUrl: null,
        envType: 'preview',
      },
    ],
  },
  {
    siteKey: 'dh-workplace-app',
    name: 'DH Workplace App',
    category: 'internal_app',
    repoUrl: 'https://github.com/dhwebservices/dh-workplace',
    githubRepo: 'dhwebservices/dh-workplace',
    cloudflareProject: 'dh-workplace',
    maintenanceSupported: true,
    workerUrl: null,
    environments: [
      {
        envKey: 'production',
        label: 'Production',
        baseUrl: 'https://app.dhworkplace.co.uk',
        healthUrl: 'https://app.dhworkplace.co.uk',
        loginUrl: 'https://app.dhworkplace.co.uk',
        envType: 'production',
      },
      {
        envKey: 'staging',
        label: 'Staging',
        baseUrl: null,
        healthUrl: null,
        envType: 'staging',
      },
      {
        envKey: 'preview',
        label: 'Preview',
        baseUrl: null,
        healthUrl: null,
        envType: 'preview',
      },
    ],
  },
  {
    siteKey: 'dhworkplace-site',
    name: 'DH Workplace Marketing Site',
    category: 'marketing_site',
    repoUrl: 'https://github.com/dhwebservices/dhworkplace',
    githubRepo: 'dhwebservices/dhworkplace',
    cloudflareProject: 'dhworkplace',
    maintenanceSupported: true,
    environments: [
      {
        envKey: 'production',
        label: 'Production',
        baseUrl: 'https://dhworkplace.co.uk',
        healthUrl: 'https://dhworkplace.co.uk',
        envType: 'production',
      },
      {
        envKey: 'preview',
        label: 'Preview',
        baseUrl: null,
        healthUrl: null,
        envType: 'preview',
      },
    ],
  },
  {
    siteKey: 'dh-website',
    name: 'DH Website Services',
    category: 'marketing_site',
    repoUrl: 'https://github.com/dhwebservices/dh-website',
    githubRepo: 'dhwebservices/dh-website',
    cloudflareProject: 'dh-website',
    maintenanceSupported: true,
    environments: [
      {
        envKey: 'production',
        label: 'Production',
        baseUrl: 'https://dhwebsiteservices.co.uk',
        healthUrl: 'https://dhwebsiteservices.co.uk',
        envType: 'production',
      },
      {
        envKey: 'preview',
        label: 'Preview',
        baseUrl: null,
        healthUrl: null,
        envType: 'preview',
      },
    ],
  },
  {
    siteKey: 'dh-clickcollect',
    name: 'DH Click & Collect',
    category: 'commerce_app',
    repoUrl: 'https://github.com/dhwebservices/dh-clickcollect',
    githubRepo: 'dhwebservices/dh-clickcollect',
    cloudflareProject: 'dh-clickcollect',
    maintenanceSupported: true,
    workerUrl: 'https://throbbing-dust-e6ea.aged-silence-66a7.workers.dev',
    environments: [
      {
        envKey: 'production',
        label: 'Production',
        baseUrl: 'https://ordermgr.dhwebsiteservices.co.uk',
        healthUrl: 'https://ordermgr.dhwebsiteservices.co.uk',
        loginUrl: 'https://ordermgr.dhwebsiteservices.co.uk/admin',
        apiUrl: 'https://throbbing-dust-e6ea.aged-silence-66a7.workers.dev',
        envType: 'production',
      },
      {
        envKey: 'preview',
        label: 'Preview',
        baseUrl: null,
        healthUrl: null,
        envType: 'preview',
      },
    ],
  },
]

export function flattenSiteEnvironments() {
  return managedSites.flatMap((site) =>
    site.environments.map((env) => ({
      ...env,
      siteKey: site.siteKey,
      siteName: site.name,
      category: site.category,
      githubRepo: site.githubRepo,
      repoUrl: site.repoUrl,
      cloudflareProject: site.cloudflareProject,
      maintenanceSupported: site.maintenanceSupported,
      workerUrl: site.workerUrl || null,
    })),
  )
}
